/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package ui;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import model.ProductManagement.Product;
import model.Supplier.Supplier;

/**
 *
 * @author manvith  
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    JPanel mainWorkArea;
    Supplier supplier;
    private Map<Product, Double> originalPrices = new HashMap<>();
private Map<Product, Double> adjustedPrices = new HashMap<>();

    
    /**
     * Creates new form ProductManagerWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel(JPanel mainWorkArea, Supplier supplier) {

        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.supplier = supplier;
        
        setPreferredSize(new Dimension(900, 800));
    
    // Make the split pane maintain its divider location
        splitPane.setResizeWeight(0.1);
          // Make sure it's enabled
           btnFinalReport.setEnabled(true);
        if (supplier != null){ lblWelcome.setText("Welcome, "+ supplier.getName());}
        refreshUI();

    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void refreshUI() {
        if (supplier != null) {
            lblWelcome.setText("Welcome, " + supplier.getName());
        }    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnPricePerformance = new javax.swing.JButton();
        btnAdjustPrice = new javax.swing.JButton();
        btnFinalReport = new javax.swing.JButton();

        splitPane.setDividerLocation(50);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setMixingCutoutShape(null);

        workArea.setBackground(new java.awt.Color(255, 255, 255));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        menuBar.setBackground(new java.awt.Color(255, 255, 255));

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblWelcome.setText("<WelcomeMsg>");

        btnPricePerformance.setText("Browse Price Performance");
        btnPricePerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPricePerformanceActionPerformed(evt);
            }
        });

        btnAdjustPrice.setText("Price Adjustment");
        btnAdjustPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjustPriceActionPerformed(evt);
            }
        });

        btnFinalReport.setText("Final Report");
        btnFinalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnPricePerformance)
                .addGap(31, 31, 31)
                .addComponent(btnAdjustPrice)
                .addGap(37, 37, 37)
                .addComponent(btnFinalReport)
                .addGap(33, 33, 33)
                .addComponent(btnLogOut)
                .addGap(88, 88, 88))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut)
                    .addComponent(lblWelcome)
                    .addComponent(btnPricePerformance)
                    .addComponent(btnAdjustPrice)
                    .addComponent(btnFinalReport))
                .addContainerGap())
        );

        splitPane.setLeftComponent(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(splitPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(splitPane))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void btnPricePerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPricePerformanceActionPerformed
        // TODO add your handling code here:
                                                            
    PricePerformanceJPanel ppjp = new PricePerformanceJPanel(workArea, supplier);
    workArea.add(ppjp, "PricePerformancePanel");
    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.show(workArea, "PricePerformancePanel");
    }//GEN-LAST:event_btnPricePerformanceActionPerformed

    private void btnAdjustPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjustPriceActionPerformed
        // TODO add your handling code here:
        PriceAdjustmentJPanel atpjp = new PriceAdjustmentJPanel(workArea,supplier);
        workArea.add("AdjustTargetPriceJPanel",atpjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAdjustPriceActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
mainWorkArea.remove(this);
    
    // Use CardLayout to switch back to login panel
    CardLayout layout = (CardLayout) mainWorkArea.getLayout();
    layout.first(mainWorkArea);
    
    // Optional: refresh the login panel if needed
    for (Component comp : mainWorkArea.getComponents()) {
        if (comp instanceof LoginMainJFrame) {
            ((LoginMainJFrame) comp).populateSupplierCombo();
        }
    }

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnFinalReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalReportActionPerformed
        // TODO add your handling code here:
      System.out.println("Final Report button clicked");
    
    // Initialize the originalPrices and adjustedPrices maps
    initializePrices();
    
    try {
        FinalReportJPanel finalReportJPanel = new FinalReportJPanel(workArea, supplier, originalPrices, adjustedPrices);
        workArea.add(finalReportJPanel, "FinalReportJPanel");
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "FinalReportJPanel");
    } catch (Exception e) {
        System.out.println("Error showing Final Report panel: " + e.getMessage());
        e.printStackTrace();
    }
}

private void initializePrices() {
    if (supplier != null && supplier.getProductCatalog() != null) {
        for (Product product : supplier.getProductCatalog().getProductList()) {
            originalPrices.put(product, (double)product.getTargetPrice());
            adjustedPrices.put(product, (double)product.getTargetPrice());
        }
    }
    }//GEN-LAST:event_btnFinalReportActionPerformed

    public String toString() {
        return "Supplier";
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        refreshUI();       
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjustPrice;
    private javax.swing.JButton btnFinalReport;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPricePerformance;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel menuBar;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
    
}
